### ISSUE TITLE
Fails with "OCI runtime exec failed: exec failed: unable to start container process: exec: "bash": executable file not found in $PATH: unknown"

### ISSUE THREAD

**Issue by ThisIsMissEm** [spicyparrot/kafka-kraft-action#14]
**Describe the bug**

Fails to find bash (I guess needed by the start/*.sh scripts?)

**To Reproduce**

Try using the action as documented; we also have the following in our workflow, but that shouldn't be the source of the issue:

```
  runs-on: ubuntu-latest

  services:
      postgres:
        # Docker Hub image
        image: postgres:16-alpine
        env:
          POSTGRES_PASSWORD: ${{ env.DATABASE_PASSWORD }}
          POSTGRES_DB: ${{ env.DATABASE_NAME }}
          POSTGRES_USER: ${{ env.DATABASE_USER }}
        ports:
          # maps tcp port 5432 on service container to the host
          - 5432:5432
        # set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
``` 

**Expected behavior**

Kafka starts, instead we get this log from the action:

```
Run spicyparrot/kafka-kraft-action@v1.1.1
  with:
    kafka-version: 3.7.0
    kafka-topics: webhook-events,1,webhook-failures,1
  env:
    ...
Run actions/checkout@v4
/usr/bin/docker exec  9e37c66c9c6ec5c97bdf1b8d36356506f35c5f824434bf80552f86d3f5570a1f sh -c "cat /etc/*release | grep ^ID"
Syncing repository: spicyparrot/kafka-kraft-action
Getting Git version info
The repository will be downloaded using the GitHub REST API
To create a local Git repository instead, add Git 2.18 or higher to the PATH
Determining the default branch
Retrieving the default branch name
Default branch 'trunk'
Downloading the archive
Writing archive to disk
Extracting the archive
/bin/tar xz -C /__w/ccs/ccs/kafka/1d4297d7-525a-45f3-8487-3210550df34e -f /__w/ccs/ccs/kafka/1d4297d7-525a-45f3-8487-3210550df34e.tar.gz
Resolved version spicyparrot-kafka-kraft-action-925b4bd
Run ./scripts/start.sh --version 3.7.0
OCI runtime exec failed: exec failed: unable to start container process: exec: "bash": executable file not found in $PATH: unknown
Error: Process completed with exit code 126.
```
